### ISSUE TITLE
Unable to build on Ubuntu 22.04.3 (linux-x64)

### ISSUE THREAD

**Issue by travisdieckmann** [gumbarros/DevWidgets#24]
Build execution log:

> $ flutter run
Connected devices:
Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 5.15.0-60-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 1
Launching lib/main.dart on Linux in debug mode...
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: Type 'DecoderCallback' not found.
ERROR:       image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
ERROR:                                                      ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: Type 'DecoderCallback' not found.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: Type 'DecoderCallback' not found.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: Type 'DecoderCallback' not found.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: Type 'DecoderCallback' not found.
ERROR:   ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
ERROR:                                          ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: Type 'DecoderCallback' not found.
ERROR:   ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
ERROR:                                                ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/kubuntu.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/kubuntu.dart:22:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/lubuntu.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/lubuntu.dart:22:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_budgie.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_budgie.dart:22:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_mate.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_mate.dart:25:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_studio.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/ubuntu_studio.dart:22:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:118:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:40:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:92:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:144:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:66:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:222:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:170:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:248:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:196:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/xubuntu.dart:9:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:24:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:131:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:53:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:105:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:157:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:79:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:235:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:183:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:261:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/yaru.dart:209:5: Error: No named parameter with the name 'primaryColorDark'.
ERROR:     primaryColorDark: YaruColors.coolGrey,
ERROR:     ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-0.3.3/lib/src/themes/xubuntu.dart:22:3: Error: No named parameter with the name 'primaryColorDark'.
ERROR:   primaryColorDark: YaruColors.coolGrey,
ERROR:   ^^^^^^^^^^^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart:462:11: Context: Found this candidate, but the arguments don't match.
ERROR:   factory ColorScheme.fromSwatch({
ERROR:           ^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:256:21: Error: The method '_TextStyleProxy.getParagraphStyle' doesn't have the named parameter 'textScaler' of overridden method 'TextStyle.getParagraphStyle'.
ERROR:   ui.ParagraphStyle getParagraphStyle({
ERROR:                     ^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/painting/text_style.dart:1328:21: Context: This is the overridden method ('getParagraphStyle').
ERROR:   ui.ParagraphStyle getParagraphStyle({
ERROR:                     ^
ERROR: ../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:288:16: Error: The method '_TextStyleProxy.getTextStyle' has fewer named arguments than those of overridden method 'TextStyle.getTextStyle'.
ERROR:   ui.TextStyle getTextStyle({double textScaleFactor = 1.0}) =>
ERROR:                ^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/painting/text_style.dart:1273:16: Context: This is the overridden method ('getTextStyle').
ERROR:   ui.TextStyle getTextStyle({
ERROR:                ^
ERROR: ../../.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.8+3/lib/fwfh_text_style.dart:274:9: Error: No named parameter with the name 'textScaleFactor'.
ERROR:         textScaleFactor: textScaleFactor,
ERROR:         ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: 'DecoderCallback' isn't a type.
ERROR:       image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
ERROR:                                                      ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: 'DecoderCallback' isn't a type.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: 'DecoderCallback' isn't a type.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: 'DecoderCallback' isn't a type.
ERROR:     DecoderCallback decode,
ERROR:     ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: 'DecoderCallback' isn't a type.
ERROR:   ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
ERROR:                                          ^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: 'DecoderCallback' isn't a type.
ERROR:   ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
ERROR:                                                ^^^^^^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed

**Comment by gumbarros** [comment]
Which version of Flutter are you using? I think I developed with Flutter 2? Anyway, I'll try to upgrade to Flutter 3 soon.

**Comment by gumbarros** [comment]
Also don't forget to run the build_runner
```dart
flutter pub run build_runner
```

**Comment by gumbarros** [comment]
@travisdieckmann 

Try a `git pull` and a build

**Comment by travisdieckmann** [comment]
Ah, yes... I initially installed Flutter 3.16.5 which is likely the issue. After I opened this issue, I discovered the AppImage release builds and am now using that instead of building myself.

That said, I did attempt to roll-back to 2.8.1 (last 2.x stable tag in the repo). This release defaults (flutter doctor) to Dart 2.15.1 which is too old for DevWidgets.
Subsequently, I switched to 2.9.0-0.1.pre (last 2.x tag in the repo). This release defaults to Dart 2.16.0 which is still too old.

Given that I have a functional app (thanks for the AppImage builds!) I'm not going to spend much more time on this as I'm not looking to contribute. This has left me with the impression that DevWidgets was built on a customized local environment which isn't obvious to replicate. For the sake of those looking to contribute to this project in the future, I would advise keeping it easy/simple by rolling with OOtB stable versions of Flutter moving forward. Please don't be offended by my unsolicited advice. I'm sure you had good reasons to do what you did. Just offering this from the eyes of a potential future contributor.

All that said, I do appreciate your hard work to bring this tool-set to Linux and look forward to using future versions!

**Comment by gumbarros** [comment]
@travisdieckmann thanks for the suggestion and words.
